<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('reports', function (Blueprint $table) {
            // AI-suggested category (generated by Gemini)
            $table->string('ai_category', 50)->nullable()->after('ai_classification');
            // Human-corrected category (takes precedence over AI)
            $table->string('manual_category', 50)->nullable()->after('ai_category');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('reports', function (Blueprint $table) {
            $table->dropColumn(['ai_category', 'manual_category']);
        });
    }
};
